#!/usr/bin/env node
/**
 * gen-seed.mjs — generates prototype/data/seed.json
 *
 * SYNTHETIC DEMO DATA. This is NOT real review-time data and must never be
 * presented as such. It exists so the prototype runs offline and so the cohort
 * maths can be verified. In production this file is replaced by the
 * user-submitted submissions table.
 *
 * Deterministic: same output every run (seeded PRNG).
 */

import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));

// --- deterministic PRNG (mulberry32) -----------------------------------------
function mulberry32(a) {
  return function () {
    a |= 0; a = (a + 0x6D2B79F5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
const rand = mulberry32(20260814);

/** Box–Muller standard normal */
function normal() {
  let u = 0, v = 0;
  while (u === 0) u = rand();
  while (v === 0) v = rand();
  return Math.sqrt(-2 * Math.log(u)) * Math.cos(2 * Math.PI * v);
}

const DAY_MS = 86400000;
const TODAY = Date.UTC(2026, 7, 14); // 2026-08-14

// --- cohort model ------------------------------------------------------------
// Lognormal waiting times: median = exp(mu), sigma controls tail heaviness.
const QUEUES = {
  apple: { label: 'Apple App Review', median: 3.2, sigma: 0.58, n: 2400 },
  google: { label: 'Google Play Review', median: 2.1, sigma: 0.62, n: 1500 },
  meta: { label: 'Meta App Review', median: 5.4, sigma: 0.66, n: 500 },
};

const PLATFORMS = {
  apple: ['ios', 'ipados', 'macos', 'tvos'],
  google: ['android'],
  meta: ['quest'],
};
const RELEASE_TYPES = ['new_app', 'update', 'hotfix', 'resubmission'];
const COUNTRY_TIERS = ['us', 'eu', 'row'];

// Additive multiplier effects (in log space, i.e. multipliers on the median).
const EFFECTS = {
  release_type: { new_app: 1.45, update: 0.88, hotfix: 0.7, resubmission: 1.12 },
  country_tier: { us: 0.92, eu: 1.0, row: 1.18 },
  first_submission: { true: 1.22, false: 0.96 },
};

// A real trend so The Queue Index has something to report:
// review times drift upward over the 120-day window (stronger for Apple).
const TREND_PER_DAY = { apple: 0.0072, google: 0.0016, meta: 0.0031 };

function pick(arr) { return arr[Math.floor(rand() * arr.length) % arr.length]; }

const rows = [];
let id = 0;

for (const [queueKey, q] of Object.entries(QUEUES)) {
  for (let i = 0; i < q.n; i++) {
    // Uniform submission date across the last 120 days.
    const daysAgo = Math.floor(rand() * 120);
    const submittedAt = TODAY - daysAgo * DAY_MS;

    const platform = pick(PLATFORMS[queueKey]);
    const releaseType = pick(RELEASE_TYPES);
    const countryTier = pick(COUNTRY_TIERS);
    const firstSubmission = rand() < 0.45;

    const mu =
      Math.log(q.median) +
      Math.log(EFFECTS.release_type[releaseType]) +
      Math.log(EFFECTS.country_tier[countryTier]) +
      Math.log(EFFECTS.first_submission[String(firstSubmission)]) +
      TREND_PER_DAY[queueKey] * (120 - daysAgo); // older submissions were faster

    const raw = Math.exp(mu + q.sigma * normal());
    const days = Math.max(0.5, Math.round(raw * 2) / 2); // half-day granularity

    rows.push({
      id: `s${String(++id).padStart(6, '0')}`,
      queue: queueKey,
      platform,
      releaseType,
      countryTier,
      firstSubmission,
      submittedAt: new Date(submittedAt).toISOString().slice(0, 10),
      daysToDecision: days,
      resolved: true,
    });
  }
}

const out = {
  _disclaimer:
    'SYNTHETIC DEMO DATA — generated by tools/gen-seed.mjs for prototype purposes only. Not real review-time data. Production replaces this with user submissions.',
  generatedAt: new Date(TODAY).toISOString(),
  windowDays: 120,
  rows,
};

const dest = resolve(__dirname, '../prototype/data/seed.json');
mkdirSync(dirname(dest), { recursive: true });
writeFileSync(dest, JSON.stringify(out));

console.log(`wrote ${rows.length} synthetic rows -> ${dest}`);
